// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookstore.Data;

#nullable disable

namespace bookstore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260424105850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("bookstore.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nguyễn Nhật Ánh"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tô Hoài"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dale Carnegie"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Robert Kiyosaki"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Paulo Coelho"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Yuval Noah Harari"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nguyễn Ngọc Tư"
                        },
                        new
                        {
                            Id = 8,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Napoleon Hill"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Trần Đắc Trung"
                        });
                });

            modelBuilder.Entity("bookstore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Câu chuyện tuổi thơ đầy cảm xúc.",
                            Image = "book1.jpg",
                            Price = 89000m,
                            PublicationYear = 2010,
                            PublisherId = 1,
                            Stock = 50,
                            Title = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tình yêu trong sáng, đơn phương.",
                            Image = "book2.jpg",
                            Price = 75000m,
                            PublicationYear = 1990,
                            PublisherId = 1,
                            Stock = 40,
                            Title = "Mắt Biếc"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cuộc phiêu lưu của chú Dế Mèn.",
                            Image = "book3.jpg",
                            Price = 45000m,
                            PublicationYear = 1941,
                            PublisherId = 2,
                            Stock = 100,
                            Title = "Dế Mèn Phiêu Lưu Ký"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nghệ thuật giao tiếp và xử thế.",
                            Image = "book4.jpg",
                            Price = 68000m,
                            PublicationYear = 1936,
                            PublisherId = 1,
                            Stock = 80,
                            Title = "Đắc Nhân Tâm"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bài học tài chính cá nhân.",
                            Image = "book5.jpg",
                            Price = 95000m,
                            PublicationYear = 1997,
                            PublisherId = 1,
                            Stock = 60,
                            Title = "Cha Giàu Cha Nghèo"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hành trình theo đuổi giấc mơ.",
                            Image = "book6.jpg",
                            Price = 59000m,
                            PublicationYear = 1988,
                            PublisherId = 5,
                            Stock = 70,
                            Title = "Nhà Giả Kim"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 6,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lịch sử loài người từ tiền sử.",
                            Image = "book7.jpg",
                            Price = 159000m,
                            PublicationYear = 2011,
                            PublisherId = 5,
                            Stock = 35,
                            Title = "Sapiens: Lược Sử Loài Người"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Truyện ngắn miền Tây Nam Bộ.",
                            Image = "book8.jpg",
                            Price = 72000m,
                            PublicationYear = 2005,
                            PublisherId = 1,
                            Stock = 45,
                            Title = "Cánh Đồng Bất Tận"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phần đầu series Harry Potter.",
                            Image = "book9.jpg",
                            Price = 120000m,
                            PublicationYear = 1997,
                            PublisherId = 1,
                            Stock = 55,
                            Title = "Harry Potter và Hòn Đá Phù Thủy"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "13 nguyên tắc làm giàu kinh điển.",
                            Image = "book10.jpg",
                            Price = 78000m,
                            PublicationYear = 1937,
                            PublisherId = 4,
                            Stock = 65,
                            Title = "Nghĩ Giàu Làm Giàu"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thế giới tuổi thơ hồn nhiên.",
                            Image = "book11.jpg",
                            Price = 65000m,
                            PublicationYear = 2008,
                            PublisherId = 1,
                            Stock = 42,
                            Title = "Cho Tôi Xin Một Vé Đi Tuổi Thơ"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bí quyết sống vui vẻ, lạc quan.",
                            Image = "book12.jpg",
                            Price = 72000m,
                            PublicationYear = 1948,
                            PublisherId = 1,
                            Stock = 38,
                            Title = "Quẳng Gánh Lo Đi Và Vui Sống"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 6,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thách thức của thế kỷ 21.",
                            Image = "book13.jpg",
                            Price = 145000m,
                            PublicationYear = 2018,
                            PublisherId = 5,
                            Stock = 30,
                            Title = "21 Bài Học Cho Thế Kỷ 21"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Phần hai series Harry Potter.",
                            Image = "book14.jpg",
                            Price = 125000m,
                            PublicationYear = 1998,
                            PublisherId = 1,
                            Stock = 48,
                            Title = "Harry Potter và Phòng Chứa Bí Mật"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bài học tài chính cho gia đình.",
                            Image = "book15.jpg",
                            Price = 85000m,
                            PublicationYear = 2000,
                            PublisherId = 1,
                            Stock = 33,
                            Title = "Dạy Con Làm Giàu - Tập 1"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xã hội Việt Nam trước cách mạng.",
                            Image = "book16.jpg",
                            Price = 35000m,
                            PublicationYear = 1937,
                            PublisherId = 6,
                            Stock = 90,
                            Title = "Tắt Đèn"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 6,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tương lai loài người với AI.",
                            Image = "book17.jpg",
                            Price = 155000m,
                            PublicationYear = 2015,
                            PublisherId = 5,
                            Stock = 28,
                            Title = "Homo Deus: Lược Sử Tương Lai"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Câu chuyện tình cảm đầy chất thơ.",
                            Image = "book18.jpg",
                            Price = 69000m,
                            PublicationYear = 2013,
                            PublisherId = 1,
                            Stock = 37,
                            Title = "Ngồi Khóc Trên Cây"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 7,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tiểu thuyết đầy chất thơ.",
                            Image = "book19.jpg",
                            Price = 68000m,
                            PublicationYear = 2012,
                            PublisherId = 1,
                            Stock = 25,
                            Title = "Sông"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giáo trình lập trình C# cho SV.",
                            Image = "book20.jpg",
                            Price = 110000m,
                            PublicationYear = 2020,
                            PublisherId = 6,
                            Stock = 75,
                            Title = "Lập Trình C# Căn Bản"
                        });
                });

            modelBuilder.Entity("bookstore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Văn học Việt Nam"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Văn học nước ngoài"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kinh tế"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kỹ năng sống"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Khoa học công nghệ"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Thiếu nhi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Giáo trình"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tâm lý - Triết học"
                        });
                });

            modelBuilder.Entity("bookstore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("bookstore.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("bookstore.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NXB Trẻ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "NXB Kim Đồng"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NXB Tổng hợp TP.HCM"
                        },
                        new
                        {
                            Id = 4,
                            Name = "NXB Lao Động"
                        },
                        new
                        {
                            Id = 5,
                            Name = "NXB Thế Giới"
                        },
                        new
                        {
                            Id = 6,
                            Name = "NXB Giáo Dục"
                        },
                        new
                        {
                            Id = 7,
                            Name = "NXB Hà Nội"
                        });
                });

            modelBuilder.Entity("bookstore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@bookstore.com",
                            IsLocked = false,
                            Name = "Admin",
                            Password = "$2a$11$K5GBBRNx0RjPJE9KAstmQeKgHfXsUW7rFm7jJhcjZzFdqzKQ5Fwi6",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user@bookstore.com",
                            IsLocked = false,
                            Name = "Nguyễn Văn A",
                            Password = "$2a$11$K5GBBRNx0RjPJE9KAstmQeKgHfXsUW7rFm7jJhcjZzFdqzKQ5Fwi6",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("bookstore.Models.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("bookstore.Models.Book", b =>
                {
                    b.HasOne("bookstore.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bookstore.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bookstore.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("bookstore.Models.Order", b =>
                {
                    b.HasOne("bookstore.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("bookstore.Models.OrderDetail", b =>
                {
                    b.HasOne("bookstore.Models.Book", "Book")
                        .WithMany("OrderDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("bookstore.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("bookstore.Models.Wishlist", b =>
                {
                    b.HasOne("bookstore.Models.Book", "Book")
                        .WithMany("Wishlists")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bookstore.Models.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("bookstore.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("bookstore.Models.Book", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("bookstore.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("bookstore.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("bookstore.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("bookstore.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
